package com.github.malyszaryczlowiek.cpcdb.alerts;

public enum ErrorFlags
{
    CONNECTION_TO_REMOTE_DB_ERROR,
    CONNECTION_TO_LOCAL_DB_ERROR,
    INCORRECT_USERNAME_OR_PASSPHRASE_TO_REMOTE_DB_ERROR,
    INCORRECT_USERNAME_OR_PASSPHRASE_TO_LOCAL_DB_ERROR
}
